<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251216113805 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE news_articles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id VARCHAR(255) NOT NULL, title VARCHAR(500) NOT NULL, description TEXT NOT NULL, content TEXT NOT NULL, source_name VARCHAR(255) NOT NULL, url VARCHAR(1000) DEFAULT NULL, image_url VARCHAR(1000) DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, language VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F6E392399F75D7B0 ON news_articles (external_id)');
        $this->addSql('CREATE INDEX idx_external_id ON news_articles (external_id)');
        $this->addSql('CREATE INDEX idx_published_at ON news_articles (published_at)');
        $this->addSql('CREATE INDEX idx_source_name ON news_articles (source_name)');
        $this->addSql('CREATE INDEX idx_language ON news_articles (language)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE news_articles');
    }
}
